plugins {
    id 'com.android.application'
}

android {
    namespace "ro.limbalatina.dictionarlatinroman"
    compileSdk 36

    defaultConfig {
        applicationId "ro.limbalatina.dictionarlatinroman"
        minSdk 23
        targetSdk 36
        versionCode 19
        versionName "5.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'     // or latest stable AppCompat
    implementation 'com.google.android.material:material:1.13.0'
}
